### ISSUE TITLE
SyntaxError

### ISSUE THREAD

**Issue by peufo** [baschni/42check#1]
Hello, je connais pas Python et je ne sais donc pas ce qu'il se passe.

Je n'arrive pas a executer le script sur les macs de l'école...

Voila mon output avec python3:
```sh
  File "/Users/jvoisard/42check/42check.py", line 47
    if (res := line.find(needle)) != -1:
            ^
SyntaxError: invalid syntax
```

Et avec python2:
```sh
  File "./42check.py", line 37
    files = [*files, *recursive_c_h_file_search(os.path.join(folder, file))]
             ^
SyntaxError: invalid syntax
```

Tu as une idée de l'erreur que je peux faire ?

**Comment by baschni** [comment]
:= is the walrus operator which makes an inline assignment. It is only available from python 3.8 onwards. I removed it from the files.

Please retest, it should work now.

**Comment by peufo** [comment]
Parfait, ca fonctionne nickel sur les mac de l'ecole 😎
